In [15]:
import numpy as np

arr=np.arange(15).reshape(3,5)
print(arr,"\n")

print("열에 관한 통계")
print(arr.mean(axis=0))

print(arr.sum(axis=0))

print(arr.min(axis=0))

print(arr.argmax(axis=0))

print("\n행에 관한 통계")
print(arr.mean(axis=1))

print(arr.sum(axis=1))

print(arr.min(axis=1))

print(arr.argmax(axis=1))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

열에 관한 통계
[5. 6. 7. 8. 9.]
[15 18 21 24 27]
[0 1 2 3 4]
[2 2 2 2 2]

행에 관한 통계
[ 2.  7. 12.]
[10 35 60]
[ 0  5 10]
[4 4 4]


In [20]:
x = np.arange(6).reshape(2,3)
print(x,"\n")

print(x+1)

[[0 1 2]
 [3 4 5]] 

[[1 2 3]
 [4 5 6]]


In [26]:
x=np.arange(15).reshape(3,5)
y=np.array([np.arange(5)])
print(x,"\n")
print(y,"\n")
print(x-y,"\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[0 1 2 3 4]] 

[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]] 



In [35]:
np.random.seed(100)
arr=np.random.randint(0,31,(5,3))
print(arr,"\n")

arr=arr.T
print(arr,"\n")

arr1=arr[:,1:4]
print(arr1,"\n")

arr1.sort(0)
print(arr1,"\n")

print(arr.mean(axis=1))

[[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]] 

[[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]] 

[[ 7 16 20]
 [23 10  2]
 [15 30 21]] 

[[ 7 10  2]
 [15 16 20]
 [23 30 21]] 

[ 5.8 15.4 18.2]


In [45]:
print(np.random.randint(0,2))

2


In [47]:
np.random.seed(0)

def make_image(m,n):
    image=np.random.randint(0,6,(m,n))
    return image

def chage_little(matrix):
    shape=matrix.shape
    for i in range(shape[0]):
        for j in range(shape[1]):
            if np.random.randint(0,2)==1:
                matrix[i][j]=np.random.randint(0,6,1)
    return matrix

image1=make_image(3,3)
print(image1,"\n")

image2=chage_little(np.copy(image1))
print(image2,"\n")

image3=image2-image1
print(image3,"\n")

image3 = np.abs(image3)
print(image3,"\n")



[[4 5 0]
 [3 3 3]
 [1 3 5]] 

[[4 5 0]
 [3 3 3]
 [0 5 5]] 

[[ 0  0  0]
 [ 0  0  0]
 [-1  2  0]] 

[[0 0 0]
 [0 0 0]
 [1 2 0]] 

